package museum.history.deerfield.centuries.database.om;

import java.util.List;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;
/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Mar 31 09:39:36 EST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ActivityPeer
    extends museum.history.deerfield.centuries.database.om.BaseActivityPeer
{

    // used by  list all
    public static List getAllActivitys(String sortBy, int status) {
    
        List activitys = null;
        Criteria crit = new Criteria();
        // show only published 2
        crit.add( ActivityPeer.STATUSID, status-1, Criteria.GREATER_THAN);

        crit.addJoin(ActivityPeer.VISITORID, VisitorPeer.VISITORID);

        if ("title".equals(sortBy)) {
            crit.addAscendingOrderByColumn(ActivityPeer.TITLE);
        } else if ("author".equals(sortBy)) {
          crit.addAscendingOrderByColumn(VisitorPeer.LASTNAME);
          crit.addAscendingOrderByColumn(VisitorPeer.FIRSTNAME);
        }
        try {
          activitys = doSelect( crit ); 
          if (activitys==null) {
              System.out.println("In ActivityPeer activitys was null");
          }
        } catch( TorqueException e ) {
          System.out.println( "Torque exception in ActivityPeer: " + e.getMessage() );
          return (null);
        }
        return (activitys);
    }


}
