package museum.history.deerfield.centuries.database.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

  
  
/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Sep 09 17:11:01 EDT 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Visitor
 */
public abstract class BaseVisitor extends BaseObject
{
    /** The Peer class */
    private static final VisitorPeer peer =
        new VisitorPeer();

        
    /** The value for the visitorID field */
    private int visitorID;
      
    /** The value for the visitorName field */
    private String visitorName;
      
    /** The value for the password field */
    private String password;
      
    /** The value for the roleID field */
    private int roleID;
      
    /** The value for the lastName field */
    private String lastName;
      
    /** The value for the firstName field */
    private String firstName;
  
    
    /**
     * Get the VisitorID
     *
     * @return int
     */
    public int getVisitorID()
    {
        return visitorID;
    }

                                              
    /**
     * Set the value of VisitorID
     *
     * @param v new value
     */
    public void setVisitorID(int v) throws TorqueException
    {
    
                  if (this.visitorID != v)
              {
            this.visitorID = v;
            setModified(true);
        }
    
          
                                  
        // update associated CollectionItem
        if (collCollectionItems != null)
        {
            for (int i = 0; i < collCollectionItems.size(); i++)
            {
                ((CollectionItem) collCollectionItems.get(i))
                    .setVisitorID(v);
            }
        }
                                          
        // update associated Activity
        if (collActivitys != null)
        {
            for (int i = 0; i < collActivitys.size(); i++)
            {
                ((Activity) collActivitys.get(i))
                    .setVisitorID(v);
            }
        }
                      }
  
    /**
     * Get the VisitorName
     *
     * @return String
     */
    public String getVisitorName()
    {
        return visitorName;
    }

                        
    /**
     * Set the value of VisitorName
     *
     * @param v new value
     */
    public void setVisitorName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.visitorName, v))
              {
            this.visitorName = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Password
     *
     * @return String
     */
    public String getPassword()
    {
        return password;
    }

                        
    /**
     * Set the value of Password
     *
     * @param v new value
     */
    public void setPassword(String v) 
    {
    
                  if (!ObjectUtils.equals(this.password, v))
              {
            this.password = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the RoleID
     *
     * @return int
     */
    public int getRoleID()
    {
        return roleID;
    }

                              
    /**
     * Set the value of RoleID
     *
     * @param v new value
     */
    public void setRoleID(int v) throws TorqueException
    {
    
                  if (this.roleID != v)
              {
            this.roleID = v;
            setModified(true);
        }
    
                          
                if (aRole != null && !(aRole.getRoleID() == v))
                {
            aRole = null;
        }
      
              }
  
    /**
     * Get the LastName
     *
     * @return String
     */
    public String getLastName()
    {
        return lastName;
    }

                        
    /**
     * Set the value of LastName
     *
     * @param v new value
     */
    public void setLastName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.lastName, v))
              {
            this.lastName = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the FirstName
     *
     * @return String
     */
    public String getFirstName()
    {
        return firstName;
    }

                        
    /**
     * Set the value of FirstName
     *
     * @param v new value
     */
    public void setFirstName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.firstName, v))
              {
            this.firstName = v;
            setModified(true);
        }
    
          
              }
  
      
    
                  
    
        private Role aRole;

    /**
     * Declares an association between this object and a Role object
     *
     * @param v Role
     * @throws TorqueException
     */
    public void setRole(Role v) throws TorqueException
    {
            if (v == null)
        {
                    setRoleID(0);
                  }
        else
        {
            setRoleID(v.getRoleID());
        }
                aRole = v;
    }

                                            
    /**
     * Get the associated Role object
     *
     * @return the associated Role object
     * @throws TorqueException
     */
    public Role getRole() throws TorqueException
    {
        if (aRole == null && (this.roleID > 0))
        {
                          aRole = RolePeer.retrieveByPK(SimpleKey.keyFor(this.roleID));
              
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Role obj = RolePeer.retrieveByPK(this.roleID);
               obj.addVisitors(this);
            */
        }
        return aRole;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
           */
    public void setRoleKey(ObjectKey key) throws TorqueException
    {
      
                        setRoleID(((NumberKey) key).intValue());
                  }
       
                                
            
    /**
     * Collection to store aggregation of collCollectionItems
     */
    protected List collCollectionItems;

    /**
     * Temporary storage of collCollectionItems to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initCollectionItems()
    {
        if (collCollectionItems == null)
        {
            collCollectionItems = new ArrayList();
        }
    }

    /**
     * Method called to associate a CollectionItem object to this object
     * through the CollectionItem foreign key attribute
     *
     * @param l CollectionItem
     * @throws TorqueException
     */
    public void addCollectionItem(CollectionItem l) throws TorqueException
    {
        getCollectionItems().add(l);
        l.setVisitor((Visitor) this);
    }

    /**
     * The criteria used to select the current contents of collCollectionItems
     */
    private Criteria lastCollectionItemsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getCollectionItems(new Criteria())
     *
     * @throws TorqueException
     */
    public List getCollectionItems() throws TorqueException
    {
        if (collCollectionItems == null)
        {
            collCollectionItems = getCollectionItems(new Criteria(10));
        }
        return collCollectionItems;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor has previously
     * been saved, it will retrieve related CollectionItems from storage.
     * If this Visitor is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getCollectionItems(Criteria criteria) throws TorqueException
    {
        if (collCollectionItems == null)
        {
            if (isNew())
            {
               collCollectionItems = new ArrayList();
            }
            else
            {
                      criteria.add(CollectionItemPeer.VISITORID, getVisitorID() );
                      collCollectionItems = CollectionItemPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(CollectionItemPeer.VISITORID, getVisitorID());
                      if (!lastCollectionItemsCriteria.equals(criteria))
                {
                    collCollectionItems = CollectionItemPeer.doSelect(criteria);
                }
            }
        }
        lastCollectionItemsCriteria = criteria;

        return collCollectionItems;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getCollectionItems(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getCollectionItems(Connection con) throws TorqueException
    {
        if (collCollectionItems == null)
        {
            collCollectionItems = getCollectionItems(new Criteria(10), con);
        }
        return collCollectionItems;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor has previously
     * been saved, it will retrieve related CollectionItems from storage.
     * If this Visitor is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getCollectionItems(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collCollectionItems == null)
        {
            if (isNew())
            {
               collCollectionItems = new ArrayList();
            }
            else
            {
                       criteria.add(CollectionItemPeer.VISITORID, getVisitorID());
                       collCollectionItems = CollectionItemPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(CollectionItemPeer.VISITORID, getVisitorID());
                       if (!lastCollectionItemsCriteria.equals(criteria))
                 {
                     collCollectionItems = CollectionItemPeer.doSelect(criteria, con);
                 }
             }
         }
         lastCollectionItemsCriteria = criteria;

         return collCollectionItems;
     }

                  
              
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor is new, it will return
     * an empty collection; or if this Visitor has previously
     * been saved, it will retrieve related CollectionItems from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Visitor.
     */
    protected List getCollectionItemsJoinVisitor(Criteria criteria)
        throws TorqueException
    {
        if (collCollectionItems == null)
        {
            if (isNew())
            {
               collCollectionItems = new ArrayList();
            }
            else
            {
                            criteria.add(CollectionItemPeer.VISITORID, getVisitorID());
                            collCollectionItems = CollectionItemPeer.doSelectJoinVisitor(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(CollectionItemPeer.VISITORID, getVisitorID());
                        if (!lastCollectionItemsCriteria.equals(criteria))
            {
                collCollectionItems = CollectionItemPeer.doSelectJoinVisitor(criteria);
            }
        }
        lastCollectionItemsCriteria = criteria;

        return collCollectionItems;
    }
                            


                          
            
    /**
     * Collection to store aggregation of collActivitys
     */
    protected List collActivitys;

    /**
     * Temporary storage of collActivitys to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initActivitys()
    {
        if (collActivitys == null)
        {
            collActivitys = new ArrayList();
        }
    }

    /**
     * Method called to associate a Activity object to this object
     * through the Activity foreign key attribute
     *
     * @param l Activity
     * @throws TorqueException
     */
    public void addActivity(Activity l) throws TorqueException
    {
        getActivitys().add(l);
        l.setVisitor((Visitor) this);
    }

    /**
     * The criteria used to select the current contents of collActivitys
     */
    private Criteria lastActivitysCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getActivitys(new Criteria())
     *
     * @throws TorqueException
     */
    public List getActivitys() throws TorqueException
    {
        if (collActivitys == null)
        {
            collActivitys = getActivitys(new Criteria(10));
        }
        return collActivitys;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor has previously
     * been saved, it will retrieve related Activitys from storage.
     * If this Visitor is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getActivitys(Criteria criteria) throws TorqueException
    {
        if (collActivitys == null)
        {
            if (isNew())
            {
               collActivitys = new ArrayList();
            }
            else
            {
                      criteria.add(ActivityPeer.VISITORID, getVisitorID() );
                      collActivitys = ActivityPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(ActivityPeer.VISITORID, getVisitorID());
                      if (!lastActivitysCriteria.equals(criteria))
                {
                    collActivitys = ActivityPeer.doSelect(criteria);
                }
            }
        }
        lastActivitysCriteria = criteria;

        return collActivitys;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getActivitys(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getActivitys(Connection con) throws TorqueException
    {
        if (collActivitys == null)
        {
            collActivitys = getActivitys(new Criteria(10), con);
        }
        return collActivitys;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor has previously
     * been saved, it will retrieve related Activitys from storage.
     * If this Visitor is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getActivitys(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collActivitys == null)
        {
            if (isNew())
            {
               collActivitys = new ArrayList();
            }
            else
            {
                       criteria.add(ActivityPeer.VISITORID, getVisitorID());
                       collActivitys = ActivityPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(ActivityPeer.VISITORID, getVisitorID());
                       if (!lastActivitysCriteria.equals(criteria))
                 {
                     collActivitys = ActivityPeer.doSelect(criteria, con);
                 }
             }
         }
         lastActivitysCriteria = criteria;

         return collActivitys;
     }

                        
              
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor is new, it will return
     * an empty collection; or if this Visitor has previously
     * been saved, it will retrieve related Activitys from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Visitor.
     */
    protected List getActivitysJoinStatus(Criteria criteria)
        throws TorqueException
    {
        if (collActivitys == null)
        {
            if (isNew())
            {
               collActivitys = new ArrayList();
            }
            else
            {
                            criteria.add(ActivityPeer.VISITORID, getVisitorID());
                            collActivitys = ActivityPeer.doSelectJoinStatus(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(ActivityPeer.VISITORID, getVisitorID());
                        if (!lastActivitysCriteria.equals(criteria))
            {
                collActivitys = ActivityPeer.doSelectJoinStatus(criteria);
            }
        }
        lastActivitysCriteria = criteria;

        return collActivitys;
    }
                  
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Visitor is new, it will return
     * an empty collection; or if this Visitor has previously
     * been saved, it will retrieve related Activitys from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Visitor.
     */
    protected List getActivitysJoinVisitor(Criteria criteria)
        throws TorqueException
    {
        if (collActivitys == null)
        {
            if (isNew())
            {
               collActivitys = new ArrayList();
            }
            else
            {
                            criteria.add(ActivityPeer.VISITORID, getVisitorID());
                            collActivitys = ActivityPeer.doSelectJoinVisitor(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(ActivityPeer.VISITORID, getVisitorID());
                        if (!lastActivitysCriteria.equals(criteria))
            {
                collActivitys = ActivityPeer.doSelectJoinVisitor(criteria);
            }
        }
        lastActivitysCriteria = criteria;

        return collActivitys;
    }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("VisitorID");
              fieldNames.add("VisitorName");
              fieldNames.add("Password");
              fieldNames.add("RoleID");
              fieldNames.add("LastName");
              fieldNames.add("FirstName");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("VisitorID"))
        {
                return new Integer(getVisitorID());
            }
          if (name.equals("VisitorName"))
        {
                return getVisitorName();
            }
          if (name.equals("Password"))
        {
                return getPassword();
            }
          if (name.equals("RoleID"))
        {
                return new Integer(getRoleID());
            }
          if (name.equals("LastName"))
        {
                return getLastName();
            }
          if (name.equals("FirstName"))
        {
                return getFirstName();
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(VisitorPeer.VISITORID))
        {
                return new Integer(getVisitorID());
            }
          if (name.equals(VisitorPeer.VISITORNAME))
        {
                return getVisitorName();
            }
          if (name.equals(VisitorPeer.PASSWORD))
        {
                return getPassword();
            }
          if (name.equals(VisitorPeer.ROLEID))
        {
                return new Integer(getRoleID());
            }
          if (name.equals(VisitorPeer.LASTNAME))
        {
                return getLastName();
            }
          if (name.equals(VisitorPeer.FIRSTNAME))
        {
                return getFirstName();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getVisitorID());
            }
              if (pos == 1)
        {
                return getVisitorName();
            }
              if (pos == 2)
        {
                return getPassword();
            }
              if (pos == 3)
        {
                return new Integer(getRoleID());
            }
              if (pos == 4)
        {
                return getLastName();
            }
              if (pos == 5)
        {
                return getFirstName();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(VisitorPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    VisitorPeer.doInsert((Visitor) this, con);
                    setNew(false);
                }
                else
                {
                    VisitorPeer.doUpdate((Visitor) this, con);
                }
            }

                                      
                
            if (collCollectionItems != null)
            {
                for (int i = 0; i < collCollectionItems.size(); i++)
                {
                    ((CollectionItem) collCollectionItems.get(i)).save(con);
                }
            }
                                          
                
            if (collActivitys != null)
            {
                for (int i = 0; i < collActivitys.size(); i++)
                {
                    ((Activity) collActivitys.get(i)).save(con);
                }
            }
                          alreadyInSave = false;
        }
      }


                          
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  visitorID ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setVisitorID(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setVisitorID(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getVisitorID());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public Visitor copy() throws TorqueException
    {
        return copyInto(new Visitor());
    }
  
    protected Visitor copyInto(Visitor copyObj) throws TorqueException
    {
          copyObj.setVisitorID(visitorID);
          copyObj.setVisitorName(visitorName);
          copyObj.setPassword(password);
          copyObj.setRoleID(roleID);
          copyObj.setLastName(lastName);
          copyObj.setFirstName(firstName);
  
                    copyObj.setVisitorID(0);
                                          
                                      
                
        List v = getCollectionItems();
        for (int i = 0; i < v.size(); i++)
        {
            CollectionItem obj = (CollectionItem) v.get(i);
            copyObj.addCollectionItem(obj.copy());
        }
                                                  
                
        v = getActivitys();
        for (int i = 0; i < v.size(); i++)
        {
            Activity obj = (Activity) v.get(i);
            copyObj.addActivity(obj.copy());
        }
                    
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public VisitorPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Visitor:\n");
        str.append("VisitorID = ")
           .append(getVisitorID())
           .append("\n");
        str.append("VisitorName = ")
           .append(getVisitorName())
           .append("\n");
        str.append("Password = ")
           .append(getPassword())
           .append("\n");
        str.append("RoleID = ")
           .append(getRoleID())
           .append("\n");
        str.append("LastName = ")
           .append(getLastName())
           .append("\n");
        str.append("FirstName = ")
           .append(getFirstName())
           .append("\n");
        return(str.toString());
    }
}
