package museum.history.deerfield.centuries.database.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Sep 09 17:11:01 EDT 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to HistoricalEraLabel
 */
public abstract class BaseHistoricalEraLabel extends BaseObject
{
    /** The Peer class */
    private static final HistoricalEraLabelPeer peer =
        new HistoricalEraLabelPeer();

        
    /** The value for the eraID field */
    private int eraID;
      
    /** The value for the label field */
    private String label;
  
    
    /**
     * Get the EraID
     *
     * @return int
     */
    public int getEraID()
    {
        return eraID;
    }

                                              
    /**
     * Set the value of EraID
     *
     * @param v new value
     */
    public void setEraID(int v) throws TorqueException
    {
    
                  if (this.eraID != v)
              {
            this.eraID = v;
            setModified(true);
        }
    
          
                                  
        // update associated HistoricalEra
        if (collHistoricalEras != null)
        {
            for (int i = 0; i < collHistoricalEras.size(); i++)
            {
                ((HistoricalEra) collHistoricalEras.get(i))
                    .setEraID(v);
            }
        }
                      }
  
    /**
     * Get the Label
     *
     * @return String
     */
    public String getLabel()
    {
        return label;
    }

                        
    /**
     * Set the value of Label
     *
     * @param v new value
     */
    public void setLabel(String v) 
    {
    
                  if (!ObjectUtils.equals(this.label, v))
              {
            this.label = v;
            setModified(true);
        }
    
          
              }
  
         
                                
            
    /**
     * Collection to store aggregation of collHistoricalEras
     */
    protected List collHistoricalEras;

    /**
     * Temporary storage of collHistoricalEras to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initHistoricalEras()
    {
        if (collHistoricalEras == null)
        {
            collHistoricalEras = new ArrayList();
        }
    }

    /**
     * Method called to associate a HistoricalEra object to this object
     * through the HistoricalEra foreign key attribute
     *
     * @param l HistoricalEra
     * @throws TorqueException
     */
    public void addHistoricalEra(HistoricalEra l) throws TorqueException
    {
        getHistoricalEras().add(l);
        l.setHistoricalEraLabel((HistoricalEraLabel) this);
    }

    /**
     * The criteria used to select the current contents of collHistoricalEras
     */
    private Criteria lastHistoricalErasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getHistoricalEras(new Criteria())
     *
     * @throws TorqueException
     */
    public List getHistoricalEras() throws TorqueException
    {
        if (collHistoricalEras == null)
        {
            collHistoricalEras = getHistoricalEras(new Criteria(10));
        }
        return collHistoricalEras;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this HistoricalEraLabel has previously
     * been saved, it will retrieve related HistoricalEras from storage.
     * If this HistoricalEraLabel is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getHistoricalEras(Criteria criteria) throws TorqueException
    {
        if (collHistoricalEras == null)
        {
            if (isNew())
            {
               collHistoricalEras = new ArrayList();
            }
            else
            {
                      criteria.add(HistoricalEraPeer.ERAID, getEraID() );
                      collHistoricalEras = HistoricalEraPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(HistoricalEraPeer.ERAID, getEraID());
                      if (!lastHistoricalErasCriteria.equals(criteria))
                {
                    collHistoricalEras = HistoricalEraPeer.doSelect(criteria);
                }
            }
        }
        lastHistoricalErasCriteria = criteria;

        return collHistoricalEras;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getHistoricalEras(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getHistoricalEras(Connection con) throws TorqueException
    {
        if (collHistoricalEras == null)
        {
            collHistoricalEras = getHistoricalEras(new Criteria(10), con);
        }
        return collHistoricalEras;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this HistoricalEraLabel has previously
     * been saved, it will retrieve related HistoricalEras from storage.
     * If this HistoricalEraLabel is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getHistoricalEras(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collHistoricalEras == null)
        {
            if (isNew())
            {
               collHistoricalEras = new ArrayList();
            }
            else
            {
                       criteria.add(HistoricalEraPeer.ERAID, getEraID());
                       collHistoricalEras = HistoricalEraPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(HistoricalEraPeer.ERAID, getEraID());
                       if (!lastHistoricalErasCriteria.equals(criteria))
                 {
                     collHistoricalEras = HistoricalEraPeer.doSelect(criteria, con);
                 }
             }
         }
         lastHistoricalErasCriteria = criteria;

         return collHistoricalEras;
     }

                        
              
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this HistoricalEraLabel is new, it will return
     * an empty collection; or if this HistoricalEraLabel has previously
     * been saved, it will retrieve related HistoricalEras from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in HistoricalEraLabel.
     */
    protected List getHistoricalErasJoinActivity(Criteria criteria)
        throws TorqueException
    {
        if (collHistoricalEras == null)
        {
            if (isNew())
            {
               collHistoricalEras = new ArrayList();
            }
            else
            {
                            criteria.add(HistoricalEraPeer.ERAID, getEraID());
                            collHistoricalEras = HistoricalEraPeer.doSelectJoinActivity(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(HistoricalEraPeer.ERAID, getEraID());
                        if (!lastHistoricalErasCriteria.equals(criteria))
            {
                collHistoricalEras = HistoricalEraPeer.doSelectJoinActivity(criteria);
            }
        }
        lastHistoricalErasCriteria = criteria;

        return collHistoricalEras;
    }
                  
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this HistoricalEraLabel is new, it will return
     * an empty collection; or if this HistoricalEraLabel has previously
     * been saved, it will retrieve related HistoricalEras from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in HistoricalEraLabel.
     */
    protected List getHistoricalErasJoinHistoricalEraLabel(Criteria criteria)
        throws TorqueException
    {
        if (collHistoricalEras == null)
        {
            if (isNew())
            {
               collHistoricalEras = new ArrayList();
            }
            else
            {
                            criteria.add(HistoricalEraPeer.ERAID, getEraID());
                            collHistoricalEras = HistoricalEraPeer.doSelectJoinHistoricalEraLabel(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(HistoricalEraPeer.ERAID, getEraID());
                        if (!lastHistoricalErasCriteria.equals(criteria))
            {
                collHistoricalEras = HistoricalEraPeer.doSelectJoinHistoricalEraLabel(criteria);
            }
        }
        lastHistoricalErasCriteria = criteria;

        return collHistoricalEras;
    }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("EraID");
              fieldNames.add("Label");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("EraID"))
        {
                return new Integer(getEraID());
            }
          if (name.equals("Label"))
        {
                return getLabel();
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(HistoricalEraLabelPeer.ERAID))
        {
                return new Integer(getEraID());
            }
          if (name.equals(HistoricalEraLabelPeer.LABEL))
        {
                return getLabel();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getEraID());
            }
              if (pos == 1)
        {
                return getLabel();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(HistoricalEraLabelPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    HistoricalEraLabelPeer.doInsert((HistoricalEraLabel) this, con);
                    setNew(false);
                }
                else
                {
                    HistoricalEraLabelPeer.doUpdate((HistoricalEraLabel) this, con);
                }
            }

                                      
                
            if (collHistoricalEras != null)
            {
                for (int i = 0; i < collHistoricalEras.size(); i++)
                {
                    ((HistoricalEra) collHistoricalEras.get(i)).save(con);
                }
            }
                          alreadyInSave = false;
        }
      }


                          
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  eraID ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setEraID(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setEraID(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getEraID());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public HistoricalEraLabel copy() throws TorqueException
    {
        return copyInto(new HistoricalEraLabel());
    }
  
    protected HistoricalEraLabel copyInto(HistoricalEraLabel copyObj) throws TorqueException
    {
          copyObj.setEraID(eraID);
          copyObj.setLabel(label);
  
                    copyObj.setEraID(0);
                  
                                      
                
        List v = getHistoricalEras();
        for (int i = 0; i < v.size(); i++)
        {
            HistoricalEra obj = (HistoricalEra) v.get(i);
            copyObj.addHistoricalEra(obj.copy());
        }
                    
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public HistoricalEraLabelPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("HistoricalEraLabel:\n");
        str.append("EraID = ")
           .append(getEraID())
           .append("\n");
        str.append("Label = ")
           .append(getLabel())
           .append("\n");
        return(str.toString());
    }
}
