package museum.history.deerfield.centuries.database.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Sep 09 17:11:01 EDT 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Role
 */
public abstract class BaseRole extends BaseObject
{
    /** The Peer class */
    private static final RolePeer peer =
        new RolePeer();

        
    /** The value for the roleID field */
    private int roleID;
      
    /** The value for the label field */
    private String label;
  
    
    /**
     * Get the RoleID
     *
     * @return int
     */
    public int getRoleID()
    {
        return roleID;
    }

                                              
    /**
     * Set the value of RoleID
     *
     * @param v new value
     */
    public void setRoleID(int v) throws TorqueException
    {
    
                  if (this.roleID != v)
              {
            this.roleID = v;
            setModified(true);
        }
    
          
                                  
        // update associated Visitor
        if (collVisitors != null)
        {
            for (int i = 0; i < collVisitors.size(); i++)
            {
                ((Visitor) collVisitors.get(i))
                    .setRoleID(v);
            }
        }
                      }
  
    /**
     * Get the Label
     *
     * @return String
     */
    public String getLabel()
    {
        return label;
    }

                        
    /**
     * Set the value of Label
     *
     * @param v new value
     */
    public void setLabel(String v) 
    {
    
                  if (!ObjectUtils.equals(this.label, v))
              {
            this.label = v;
            setModified(true);
        }
    
          
              }
  
         
                                
            
    /**
     * Collection to store aggregation of collVisitors
     */
    protected List collVisitors;

    /**
     * Temporary storage of collVisitors to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initVisitors()
    {
        if (collVisitors == null)
        {
            collVisitors = new ArrayList();
        }
    }

    /**
     * Method called to associate a Visitor object to this object
     * through the Visitor foreign key attribute
     *
     * @param l Visitor
     * @throws TorqueException
     */
    public void addVisitor(Visitor l) throws TorqueException
    {
        getVisitors().add(l);
        l.setRole((Role) this);
    }

    /**
     * The criteria used to select the current contents of collVisitors
     */
    private Criteria lastVisitorsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getVisitors(new Criteria())
     *
     * @throws TorqueException
     */
    public List getVisitors() throws TorqueException
    {
        if (collVisitors == null)
        {
            collVisitors = getVisitors(new Criteria(10));
        }
        return collVisitors;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Role has previously
     * been saved, it will retrieve related Visitors from storage.
     * If this Role is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getVisitors(Criteria criteria) throws TorqueException
    {
        if (collVisitors == null)
        {
            if (isNew())
            {
               collVisitors = new ArrayList();
            }
            else
            {
                      criteria.add(VisitorPeer.ROLEID, getRoleID() );
                      collVisitors = VisitorPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(VisitorPeer.ROLEID, getRoleID());
                      if (!lastVisitorsCriteria.equals(criteria))
                {
                    collVisitors = VisitorPeer.doSelect(criteria);
                }
            }
        }
        lastVisitorsCriteria = criteria;

        return collVisitors;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getVisitors(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getVisitors(Connection con) throws TorqueException
    {
        if (collVisitors == null)
        {
            collVisitors = getVisitors(new Criteria(10), con);
        }
        return collVisitors;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Role has previously
     * been saved, it will retrieve related Visitors from storage.
     * If this Role is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getVisitors(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collVisitors == null)
        {
            if (isNew())
            {
               collVisitors = new ArrayList();
            }
            else
            {
                       criteria.add(VisitorPeer.ROLEID, getRoleID());
                       collVisitors = VisitorPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(VisitorPeer.ROLEID, getRoleID());
                       if (!lastVisitorsCriteria.equals(criteria))
                 {
                     collVisitors = VisitorPeer.doSelect(criteria, con);
                 }
             }
         }
         lastVisitorsCriteria = criteria;

         return collVisitors;
     }

                  
              
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Role is new, it will return
     * an empty collection; or if this Role has previously
     * been saved, it will retrieve related Visitors from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Role.
     */
    protected List getVisitorsJoinRole(Criteria criteria)
        throws TorqueException
    {
        if (collVisitors == null)
        {
            if (isNew())
            {
               collVisitors = new ArrayList();
            }
            else
            {
                            criteria.add(VisitorPeer.ROLEID, getRoleID());
                            collVisitors = VisitorPeer.doSelectJoinRole(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(VisitorPeer.ROLEID, getRoleID());
                        if (!lastVisitorsCriteria.equals(criteria))
            {
                collVisitors = VisitorPeer.doSelectJoinRole(criteria);
            }
        }
        lastVisitorsCriteria = criteria;

        return collVisitors;
    }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("RoleID");
              fieldNames.add("Label");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("RoleID"))
        {
                return new Integer(getRoleID());
            }
          if (name.equals("Label"))
        {
                return getLabel();
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(RolePeer.ROLEID))
        {
                return new Integer(getRoleID());
            }
          if (name.equals(RolePeer.LABEL))
        {
                return getLabel();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getRoleID());
            }
              if (pos == 1)
        {
                return getLabel();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(RolePeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    RolePeer.doInsert((Role) this, con);
                    setNew(false);
                }
                else
                {
                    RolePeer.doUpdate((Role) this, con);
                }
            }

                                      
                
            if (collVisitors != null)
            {
                for (int i = 0; i < collVisitors.size(); i++)
                {
                    ((Visitor) collVisitors.get(i)).save(con);
                }
            }
                          alreadyInSave = false;
        }
      }


                          
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  roleID ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setRoleID(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setRoleID(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getRoleID());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public Role copy() throws TorqueException
    {
        return copyInto(new Role());
    }
  
    protected Role copyInto(Role copyObj) throws TorqueException
    {
          copyObj.setRoleID(roleID);
          copyObj.setLabel(label);
  
                    copyObj.setRoleID(0);
                  
                                      
                
        List v = getVisitors();
        for (int i = 0; i < v.size(); i++)
        {
            Visitor obj = (Visitor) v.get(i);
            copyObj.addVisitor(obj.copy());
        }
                    
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public RolePeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Role:\n");
        str.append("RoleID = ")
           .append(getRoleID())
           .append("\n");
        str.append("Label = ")
           .append(getLabel())
           .append("\n");
        return(str.toString());
    }
}
