
package museum.history.deerfield.centuries.database.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Mar 31 09:39:36 EST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Role
    extends museum.history.deerfield.centuries.database.om.BaseRole
    implements Persistent
{
}
