package museum.history.deerfield.centuries.database.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Sep 09 17:11:01 EDT 2010]
  *
  */
public class ActivityMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "museum.history.deerfield.centuries.database.om.map.ActivityMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("centuriesForum");

        dbMap.addTable("Activity");
        TableMap tMap = dbMap.getTable("Activity");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);


              tMap.addPrimaryKey("Activity.ACTIVITYID", new Integer(0));
                    tMap.addForeignKey(
                "Activity.STATUSID", new Integer(0) , "Status" ,
                "statusID");
                    tMap.addForeignKey(
                "Activity.VISITORID", new Integer(0) , "Visitor" ,
                "visitorID");
                    tMap.addColumn("Activity.TITLE", new String());
                    tMap.addColumn("Activity.SHORTDESCRIPTION", new String());
                    tMap.addColumn("Activity.LONGDESCRIPTION", new String());
                    tMap.addColumn("Activity.SUBMITTEDON", new Date());
          }
}
